[package]
name = "chip8-rs"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "chip8-tui",
  "chip8-core"
]

[dependencies]
chip8-core = { path = "./chip8-core" }
chip8-tui = { path = "./chip8-tui" }
